# Develop override settings
# Usage: bundle exec jekyll serve --config _config.yml,_config.dev.yml

url: http://localhost:4000
baseurl: ""

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded